services:
  strapi-cms:
    container_name: strapi-cms
    build:
      context: .
      args:
        NODE_ENV: production
        PUBLIC_URL: ${PUBLIC_URL}
    image: strapi-cms:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: strapi-cms-db
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    depends_on:
      - strapi-cms-db
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:1337/_health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  strapi-cms-db:
    container_name: strapi-cms-db
    platform: linux/arm64/v8
    restart: unless-stopped
    env_file: .env
    image: mariadb:latest
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - strapi-cms-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    platform: linux/arm64/v8
    restart: unless-stopped
    environment:
      - PMA_HOST=strapi-cms-db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=1000000000000000
      - APACHE_PORT=8081
    ports:
      - '8081:8081'
    depends_on:
      - strapi-cms-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  strapi-cms-data:
