name: CI bench (temporary)

on:
    push:
        branches:
            - chore/ci-faster
        paths:
            - '.github/workflows/ci-bench.yml'

permissions:
    contents: read

jobs:
    store:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v7
            - uses: voidzero-dev/setup-vp@v1.21.1
              with:
                  cache: true
                  cache-save: false
    modules:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v7
            - uses: ./.github/actions/setup-deps
            - run: vp check
            - run: vp test run
